[toolchain]
anchor_version = "0.32.1"
solana_version = "3.0.13"

[features]
seeds = true
skip-lint = false

[programs.localnet]
agenc_coordination = "EopUaCV2svxj9j4hd7KjbrWfdjkspmm2BCBe7jGpKzKZ"

[programs.devnet]
agenc_coordination = "EopUaCV2svxj9j4hd7KjbrWfdjkspmm2BCBe7jGpKzKZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 30000

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 180000 tests/test_1.ts"

[workspace]
members = ["programs/agenc-coordination"]
