[package]
name = "agenc-guest"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
risc0-zkvm = { version = "~3.0", default-features = false, features = ["std"] }
agenc-zkvm-guest = { path = "../../guest" }
