task_id = [177, 188, 186, 193, 204, 173, 218, 66, 226, 97, 59, 68, 77, 0, 51, 158, 227, 195, 210, 219, 42, 44, 0, 108, 125, 133, 53, 219, 220, 15, 9, 135]
agent_pubkey = [50, 81, 31, 129, 183, 40, 6, 233, 199, 157, 254, 227, 118, 7, 189, 237, 70, 31, 226, 35, 112, 177, 88, 169, 137, 54, 126, 171, 149, 218, 22, 159]
output = ["1", "2", "3", "4"]
salt = "12345"
